[package]
name = "rgame"
version = "0.0.1"
authors = ["Connor Hilarides <connorcpu@live.com>"]

[dependencies]
ecs = "*"
image = "*"
glutin = "*"
glium = "*"

[dependencies.time]
git = "https://github.com/rust-lang/time.git"

[dependencies.glium_macros]
git = "https://github.com/tomaka/glium.git"
